speak_limit_per_minutes:
  name: 発言回数制限 何分あたり？
  type: integer
  default: 20

speak_limit_counts:
  name: 発言回数制限 何回？
  type: integer
  default: 10

admin_message:
  name: 管理者からひとこと
  type: string

# site_title:
#   name: Site Title
#   default: My Site
#   type: string
#   
# site_description:
#   name: Description for Google
#   default: Lots of Awesomeness Here
#   type: text
#   
# secret:
#   name: Secret Password for Accessing Secret Areas
#   default: secret
#   type: password